DROP TABLE IF EXISTS modification;
DROP TABLE IF EXISTS menuInfo;
DROP TABLE IF EXISTS orderItem;
DROP TABLE IF EXISTS orderTest;
DROP TABLE IF EXISTS menu;
DROP TABLE IF EXISTS inventory;
DROP TABLE IF EXISTS employee;
DROP TABLE IF EXISTS locationTable;